// Generat automàticament | Data: 2026-06-18

const ALLOTJAMENTS = {
  "alj-smi-01": {
    "nom": "Santo Cristo House",
    "illa": "Sao Miguel",
    "localitat": "Ponta Delgada",
    "adreca": "Rua São Francisco Xavier nº 8, 9500-243",
    "tel": "+351 969 359 139",
    "punt": 8.8,
    "entrada": "2026-07-22",
    "sortida": "2026-07-24",
    "nits": 2,
    "h_arr": "21:30h",
    "h_sor": "Abans de les 12h",
    "cost": 374.0,
    "cost_nit": 187.0,
    "tipus": "Casa sencera",
    "reserva": "6927405020",
    "pin": "9024",
    "cancel": null,
    "pag": "2026-04-22",
    "hab": 3,
    "llits": "2 llits dobles i 2 llits individuals",
    "banys": 3,
    "equip": "Terrassa, Aire condicionat, Cuina, Tovalloles, Llençols, Endoll a prop del llit, Productes de neteja, Escriptori, TV, Nevera, Mosquitera, Telèfon, Canals per satèl·lit, Cafetera, Planxa, Microones, Calefacció, TV de pantalla plana, Assecador, Estris de cuina, Lavabo addicional, Bullidor elèctric, Mobles d'exterior, Zona de menjador exterior, Canals per cable, Armari, Forn, Fogons, Torradora, Zona de menjador, Taula de menjador, Plantes superiors només accessibles per les escales, Penjador de roba, Llit desplegable, Estenedor de roba, Paper de vàter, Jocs de taula o puzzles, Llibres, DVD o música per a nens, Aire condicionat individual per a cada habitació de l'allotjament",
    "idioma": "PT; EN",
    "link": "https://www.booking.com/hotel/pt/santo-cristo-house.ca.html",
    "fotos": "SantoCristoXX.jpg",
    "zona": "Ponta Delgada",
    "wifi": true,
    "ac": true,
    "rentadora": true,
    "destacat": "Terrassa"
  },
  "alj-smi-02": {
    "nom": "Casa Cherimoya - Your Retreat by the Sea",
    "illa": "Sao Miguel",
    "localitat": "Ribeira das Tainhas",
    "adreca": "Rua Outeiro dos Álamos Brancos 26, 9680-512",
    "tel": "+351 964 737 851",
    "punt": null,
    "entrada": "2026-07-24",
    "sortida": "2026-07-28",
    "nits": 4,
    "h_arr": "A partir de les 17h",
    "h_sor": "5:30h",
    "cost": 916.8,
    "cost_nit": 229.2,
    "tipus": "Casa sencera",
    "reserva": "5834821478",
    "pin": "7232",
    "cancel": "2026-06-23",
    "pag": "2026-06-22",
    "hab": 3,
    "llits": "2 llits dobles grans, 2 llits dobles i 1 sofà llit",
    "banys": 2,
    "equip": "Balcó,  Aire condicionat, Cuina, Rentadora, Sofà, Parquet, Tovalloles, Endoll a prop del llit, Escriptori, Zona d'estar, Insonorització, Entrada privada, TV, Nevera, Mosquitera, Estris per planxar, Cafetera, Planxa, Microones, Calefacció, TV de pantalla plana, Ventilador, Bullidor elèctric, Mobles d'exterior, Rentaplats, Assecadora, Armari, Forn, Fogons, Torradora, Barbacoa, Zona de menjador, Plantes superiors només accessibles per les escales, Adossat, Penjador de roba, Estenedor de roba, Sofà llit, Aire condicionat individual per a cada habitació de l'allotjament",
    "idioma": "PT; EN",
    "link": "https://www.booking.com/hotel/pt/casa-cherimoya-your-retreat-by-the-sea.ca.html",
    "fotos": "CherimoyaXX.jpg",
    "zona": "Vila Franca do Campo",
    "wifi": true,
    "ac": true,
    "rentadora": true,
    "destacat": "Casa de 300m2"
  },
  "alj-pic-01": {
    "nom": "Prainha Apartments",
    "illa": "Pico",
    "localitat": "São Roque do Pico",
    "adreca": "9940 Canto da Areia",
    "tel": "+351 919 300 677",
    "punt": 7.7,
    "entrada": "2026-07-28",
    "sortida": "2026-07-31",
    "nits": 3,
    "h_arr": "22:30h",
    "h_sor": "Abans de les 12h",
    "cost": 852.0,
    "cost_nit": 284.0,
    "tipus": "Apartament (2)",
    "reserva": "6179234145",
    "pin": "5053",
    "cancel": "2026-06-27",
    "pag": "2026-06-26",
    "hab": 1,
    "llits": "3 llits individuals",
    "banys": 1,
    "equip": "Cuina, Bidet, Rentadora, Lavabo, Sofà, Dutxa o banyera, Tovalloles, Llençols, Endoll a prop del llit, Productes de neteja, Entrada privada, TV, Nevera, Mosquitera, Cafetera, Planxa, TV de pantalla plana, Assecador, Estris de cuina, Bullidor elèctric, Pati, Armari, Fogons, Torradora, Zona de menjador, Taula de menjador, Tot l'allotjament està situat a la planta baixa, Independent, Apartament privat en un edifici, Penjador de roba, Estenedor de roba, Paper de vàter",
    "idioma": "PT; EN; ES",
    "link": "https://www.booking.com/hotel/pt/prainha-apartments.ca.html",
    "fotos": "PrainhaXX.jpg",
    "zona": "Sao Roque do Pico",
    "wifi": false,
    "ac": false,
    "rentadora": false,
    "destacat": "Platja"
  },
  "alj-fai-01": {
    "nom": "Refúgio",
    "illa": "Faial",
    "localitat": "Horta",
    "adreca": "Quinhoes, Nº 19 Feteira, 9900-361",
    "tel": "+351 969 134 555",
    "punt": 9.1,
    "entrada": "2026-07-31",
    "sortida": "2026-08-02",
    "nits": 2,
    "h_arr": "A partir de les 15h",
    "h_sor": "9h",
    "cost": 470.0,
    "cost_nit": 235.0,
    "tipus": "Casa sencera",
    "reserva": "5907923608",
    "pin": "1971",
    "cancel": null,
    "pag": "2026-04-22",
    "hab": 4,
    "llits": "3 llits dobles i 2 llits individuals",
    "banys": 2,
    "equip": "Cuina, Bidet, Rentadora, Lavabo, Sofà, Dutxa o banyera, Parquet, Tovalloles, Llençols, Endoll a prop del llit, Productes de neteja, Zona d'estar, Entrada privada, TV, Nevera, Cafetera, Microones, TV de pantalla plana, Assecador, Estris de cuina, Ventilador, Bullidor elèctric, Mobles d'exterior, Zona de menjador exterior, Pati, Canals per cable, Piscina privada, Armari, Forn, Fogons, Torradora, Zona de menjador, Taula de menjador, Plantes superiors només accessibles per les escales, Independent, Penjador de roba, Estenedor de roba, Paper de vàter",
    "idioma": "PT; EN",
    "link": "https://www.booking.com/hotel/pt/refugio.ca.html",
    "fotos": "Refugio.jpg",
    "zona": "Horta",
    "wifi": true,
    "ac": true,
    "rentadora": true,
    "destacat": "Piscina"
  }
};
