// Generat automàticament | Data: 2026-06-18

const EXCURSIONS = {
  "ex-vai-smi-01": {
    "illa": "Sao Miguel",
    "sub": "barco",
    "nom": "Posta de sol a Mosteiros",
    "zona": "Mosteiros",
    "emoji": "⛵",
    "destacat": false,
    "info": "Zodiac",
    "sortides": "1 hora abans de la posta de sol",
    "durada": "1h",
    "preu": 31.73,
    "empresa": "https://terradopico.com/tours/sunset-cruise/"
  },
  "ex-vai-smi-02": {
    "illa": "Sao Miguel",
    "sub": "barco",
    "nom": "Explorar la costa de Mosteiros",
    "zona": "Mosteiros",
    "emoji": "⛵",
    "destacat": false,
    "info": "Zodiac",
    "sortides": "17:30h",
    "durada": "1h",
    "preu": 26.44,
    "empresa": "https://terradopico.com/tours/coastline-cruise/"
  },
  "ex-vai-smi-03": {
    "illa": "Sao Miguel",
    "sub": "barco",
    "nom": "Coves, penya-segats i història local (en castellà)",
    "zona": "Rabo de Peixe",
    "emoji": "⛵",
    "destacat": true,
    "info": "Zodiac",
    "sortides": "9:30-14",
    "durada": "3h",
    "preu": 69.9,
    "empresa": "https://azoreanseascape.pt/es/libro/?re-product-id=334185"
  },
  "ex-vai-smi-04": {
    "illa": "Sao Miguel",
    "sub": "barco",
    "nom": "Sunset - Coves Volcàniques i Llum Daurada (en castellà)",
    "zona": "Rabo de Peixe",
    "emoji": "⛵",
    "destacat": false,
    "info": "Zodiac",
    "sortides": "19h",
    "durada": "1,5-2h",
    "preu": 72.0,
    "empresa": "https://azoreanseascape.pt/es/libro/?re-product-id=334607&rwstep=product"
  },
  "ex-vai-smi-05": {
    "illa": "Sao Miguel",
    "sub": "barco",
    "nom": "Arcs de Capelas i Trompa de l'Elefant (en castellà)",
    "zona": "Rabo de Peixe",
    "emoji": "⛵",
    "destacat": true,
    "info": "Zodiac",
    "sortides": "9:30",
    "durada": "2-2,5h",
    "preu": 62.0,
    "empresa": "https://azoreanseascape.pt/es/libro/?re-product-id=334660&rwstep=product"
  },
  "ex-vai-smi-06": {
    "illa": "Sao Miguel",
    "sub": "barco",
    "nom": "Excursió amb vaixell amb fons de vidre + snorkel",
    "zona": "Vila Franca do Campo",
    "emoji": "⛵",
    "destacat": false,
    "info": "Catamarà",
    "sortides": "9:30 i 14:30",
    "durada": "2h",
    "preu": 52.88,
    "empresa": "https://oceaneyeazores.pt/es/paseo-en-barco-con-fondo-de-cristal/"
  },
  "ex-vai-smi-07": {
    "illa": "Sao Miguel",
    "sub": "barco",
    "nom": "Passeig amb vaixell al voltant de l'illot de Vila Franca do Campo",
    "zona": "Vila Franca do Campo",
    "emoji": "⛵",
    "destacat": false,
    "info": "Catamarà",
    "sortides": "Dt, Dj, Ds i Dg a les 9:30",
    "durada": "45min",
    "preu": 26.44,
    "empresa": "https://oceaneyeazores.pt/es/"
  },
  "ex-vai-smi-08": {
    "illa": "Sao Miguel",
    "sub": "barco",
    "nom": "Una aventura a través de coves marines amagades de la costa nord",
    "zona": "Rabo de Peixe",
    "emoji": "⛵",
    "destacat": false,
    "info": "Barca petita",
    "sortides": "9:30",
    "durada": "3h",
    "preu": 75.0,
    "empresa": "https://www.azoresboatadventures.com/"
  },
  "ex-vai-smi-09": {
    "illa": "Sao Miguel",
    "sub": "barco",
    "nom": "Visita a la cova del capvespre. Una posta de sol màgica a l'Atlàntic",
    "zona": "Rabo de Peixe",
    "emoji": "⛵",
    "destacat": false,
    "info": "Barca petita",
    "sortides": "S'ha de trucar per reservar i saber el preu",
    "durada": "3h",
    "preu": "n/d",
    "empresa": "https://www.azoresboatadventures.com/"
  },
  "ex-vai-smi-10": {
    "illa": "Sao Miguel",
    "sub": "barco",
    "nom": "Recorregut en vaixell per l'illot de Vila Franca do Campo",
    "zona": "Vila Franca do Campo",
    "emoji": "⛵",
    "destacat": false,
    "info": "Zodiac",
    "sortides": "17:30",
    "durada": "30 min",
    "preu": 31.55,
    "empresa": "https://www.azoressub.com/en/tours/islet-boat-tour/"
  },
  "ex-vai-smi-11": {
    "illa": "Sao Miguel",
    "sub": "barco",
    "nom": "Illot de Vila Franca do Campo",
    "zona": "Vila Franca do Campo",
    "emoji": "⛵",
    "destacat": false,
    "info": "Zodiac",
    "sortides": "De 9:30h a 17:30h cada hora",
    "durada": "1h",
    "preu": 28.0,
    "empresa": "https://www.azoreswhalewatch.com/vila-franca-islet-tickets"
  },
  "ex-vai-smi-12": {
    "illa": "Sao Miguel",
    "sub": "barco",
    "nom": "Passeig amb vaixell amb fons de vidre",
    "zona": "Vila Franca do Campo",
    "emoji": "⛵",
    "destacat": false,
    "info": "Catamarà",
    "sortides": "9:30h i 14:30h",
    "durada": "2h",
    "preu": 52.88,
    "empresa": "https://oceaneyeazores.pt/es/paseo-en-barco-con-fondo-de-cristal/"
  },
  "ex-vai-smi-13": {
    "illa": "Sao Miguel",
    "sub": "barco",
    "nom": "Coves marines i penya-segats volcànics",
    "zona": "Rabo de Peixe",
    "emoji": "⛵",
    "destacat": false,
    "info": "Zodiac",
    "sortides": "9:30",
    "durada": "2h",
    "preu": 49.0,
    "empresa": "https://agexpeditions.pt/es-eu/tours/wild-north-coast-boat-tour"
  },
  "ex-vai-smi-14": {
    "illa": "Sao Miguel",
    "sub": "barco",
    "nom": "Tour al capvespre i nedar",
    "zona": "Rabo de Peixe",
    "emoji": "⛵",
    "destacat": false,
    "info": "Zodiac",
    "sortides": "De Dv. a Dg. 18:30",
    "durada": "1,5h",
    "preu": 59.0,
    "empresa": "https://agexpeditions.pt/es-eu/tours/wild-north-coast-boat-tour"
  },
  "ex-cet-smi-01": {
    "illa": "Sao Miguel",
    "sub": "cetacis",
    "nom": "Avistament de cetacis",
    "zona": "Ponta Delgada",
    "emoji": "🐋",
    "destacat": false,
    "info": "Opció Catamarà o Zodiac",
    "sortides": "8h, 8:30h, 9h, 12:30h, 13h, 13:30h",
    "durada": "3h",
    "preu": 70.0,
    "empresa": "https://www.futurismo.pt/es/visitas/avistamiento-de-cetaceos-en-ponta-delgada-sao-miguel-azores/"
  },
  "ex-cet-smi-02": {
    "illa": "Sao Miguel",
    "sub": "cetacis",
    "nom": "Avistament de cetacis amb vaixell amb fons de vidre",
    "zona": "Ponta Delgada",
    "emoji": "🐋",
    "destacat": false,
    "info": "Catamarà",
    "sortides": "9h i 14h",
    "durada": "3h",
    "preu": 60.0,
    "empresa": "https://www.mobydick-tours.com"
  },
  "ex-cet-smi-03": {
    "illa": "Sao Miguel",
    "sub": "cetacis",
    "nom": "Avistament de balenes i dofins",
    "zona": "Ponta Delgada",
    "emoji": "🐋",
    "destacat": false,
    "info": "Opció Catamarà o Zodiac",
    "sortides": "8:30, 9:00, 13:00 i 13:30",
    "durada": "3h",
    "preu": 74.2,
    "empresa": "https://picosdeaventura.com/pt/tour/observacao-de-baleias-e-golfinhos/"
  },
  "ex-cet-smi-04": {
    "illa": "Sao Miguel",
    "sub": "cetacis",
    "nom": "Avistament de cetacis",
    "zona": "Rabo de Peixe",
    "emoji": "🐋",
    "destacat": false,
    "info": "Zodiac",
    "sortides": "8:30h i 13:30h",
    "durada": "3h",
    "preu": 70.0,
    "empresa": "https://www.futurismo.pt/es/visitas/avistamiento-de-cetaceos-en-rabo-de-peixe-sao-miguel-azores/"
  },
  "ex-cet-smi-05": {
    "illa": "Sao Miguel",
    "sub": "cetacis",
    "nom": "Avistament de cetacis i Illot de Vila Franca do Campo",
    "zona": "Ponta Delgada",
    "emoji": "🐋",
    "destacat": false,
    "info": "Zodiac",
    "sortides": "8h",
    "durada": "8h",
    "preu": 117.0,
    "empresa": "https://www.futurismo.pt/es/visitas/avistamiento-de-cetaceos-islote-de-vila-franca-sao-miguel-azores/"
  },
  "ex-cet-smi-06": {
    "illa": "Sao Miguel",
    "sub": "cetacis",
    "nom": "Avistament de cetacis",
    "zona": "Vila Franca do Campo",
    "emoji": "🐋",
    "destacat": false,
    "info": "Zodiac",
    "sortides": "8:30h, 9h, 12:30h, 13h i 15:40h",
    "durada": "3h",
    "preu": 78.0,
    "empresa": "https://www.azoreswhalewatch.com/whale-watching-azores"
  },
  "ex-cet-smi-07": {
    "illa": "Sao Miguel",
    "sub": "cetacis",
    "nom": "Avistament de cetacis",
    "zona": "Vila Franca do Campo",
    "emoji": "🐋",
    "destacat": false,
    "info": "Opció Catamarà o Zodiac",
    "sortides": "Dc i Dv a les 9h",
    "durada": "3-4h",
    "preu": 62.4,
    "empresa": "https://oceaneyeazores.pt/es/avistamiento-de-ballenas-y-delfines/"
  },
  "ex-cet-smi-08": {
    "illa": "Sao Miguel",
    "sub": "cetacis",
    "nom": "Avistament de cetacis",
    "zona": "Mosteiros",
    "emoji": "🐋",
    "destacat": false,
    "info": "Zodiac",
    "sortides": "9h i 14:30h",
    "durada": "2,5h",
    "preu": 74.04,
    "empresa": "https://terradopico.com/tours/whale-watching/"
  },
  "ex-est-smi-01": {
    "illa": "Sao Miguel",
    "sub": "estrelles",
    "nom": "Estrelles - Lagoa do Fogo (Mirador de Pico Barrosa)",
    "zona": "Lagoa do Fogo",
    "emoji": "✨",
    "destacat": false,
    "info": "A 800 m., per sobre de la boira baixa",
    "sortides": null,
    "durada": null,
    "preu": null,
    "empresa": null
  },
  "ex-est-smi-02": {
    "illa": "Sao Miguel",
    "sub": "estrelles",
    "nom": "Estrelles - Nordeste (Pico do Bartolomeu)",
    "zona": "Nordeste",
    "emoji": "✨",
    "destacat": false,
    "info": "Punta NE, molt fosc",
    "sortides": null,
    "durada": null,
    "preu": null,
    "empresa": null
  },
  "ex-est-smi-03": {
    "illa": "Sao Miguel",
    "sub": "estrelles",
    "nom": "Estrelles - Mirador de Pico do Carvao",
    "zona": "Sete Cidades",
    "emoji": "✨",
    "destacat": false,
    "info": "Visió neta de 360 graus, sense llums",
    "sortides": null,
    "durada": null,
    "preu": null,
    "empresa": null
  },
  "ex-cet-pic-01": {
    "illa": "Pico",
    "sub": "cetacis",
    "nom": "Avistament de cetacis",
    "zona": "Lajes do Pico",
    "emoji": "🐋",
    "destacat": true,
    "info": "Zodiac",
    "sortides": "8:30h i 13:30h",
    "durada": "3h",
    "preu": 70.0,
    "empresa": "https://www.futurismo.pt/es/actividades/avistamiento-de-ballenas-en-azores/?island=pico-island-azores"
  },
  "ex-cet-pic-02": {
    "illa": "Pico",
    "sub": "cetacis",
    "nom": "Avistament de cetacis",
    "zona": "Lajes do Pico",
    "emoji": "🐋",
    "destacat": true,
    "info": "Opció Catamarà o Zodiac",
    "sortides": "9h i 14h",
    "durada": "2,5h",
    "preu": 75.0,
    "empresa": "https://aquaacores.pt/"
  },
  "ex-cet-pic-03": {
    "illa": "Pico",
    "sub": "cetacis",
    "nom": "Avistament de cetacis",
    "zona": "Lajes do Pico",
    "emoji": "🐋",
    "destacat": true,
    "info": "Zodiac",
    "sortides": "9h i 14h",
    "durada": "3h",
    "preu": 75.0,
    "empresa": "https://espacotalassa.com/en/whale-watching/"
  },
  "ex-cet-pic-04": {
    "illa": "Pico",
    "sub": "cetacis",
    "nom": "Avistament de cetacis",
    "zona": "Madalena",
    "emoji": "🐋",
    "destacat": false,
    "info": "Opció Catamarà o Zodiac",
    "sortides": "9h, 14h i 17:30h",
    "durada": "3h",
    "preu": 79.0,
    "empresa": "https://www.pico-island-adventures.com/"
  },
  "ex-cet-pic-05": {
    "illa": "Pico",
    "sub": "cetacis",
    "nom": "Avistament de cetacis",
    "zona": "Madalena",
    "emoji": "🐋",
    "destacat": false,
    "info": "Zodiac",
    "sortides": null,
    "durada": "3-4h",
    "preu": 79.0,
    "empresa": "https://www.cwazores.com/whale-watching"
  },
  "ex-cet-pic-06": {
    "illa": "Pico",
    "sub": "cetacis",
    "nom": "Avistament de cetacis",
    "zona": "Madalena",
    "emoji": "🐋",
    "destacat": false,
    "info": "Zodiac",
    "sortides": "9:30h i 14:30h",
    "durada": "3h",
    "preu": 80.0,
    "empresa": "https://www.naturalist.pt/uk-tour-azores-whale-watching"
  },
  "ex-est-pic-01": {
    "illa": "Pico",
    "sub": "estrelles",
    "nom": "Estrelles - Casa da Montanha",
    "zona": "Montanha do Pico",
    "emoji": "✨",
    "destacat": true,
    "info": "1.200m. Vistes espectaculars",
    "sortides": null,
    "durada": null,
    "preu": null,
    "empresa": null
  },
  "ex-est-pic-02": {
    "illa": "Pico",
    "sub": "estrelles",
    "nom": "Estrelles - Lagoa do Capitao",
    "zona": "Planalto da Achada",
    "emoji": "✨",
    "destacat": true,
    "info": "Entorn molt fosc ideal per veure la Via Làctia reflectida sobre l'aigua",
    "sortides": null,
    "durada": null,
    "preu": null,
    "empresa": null
  },
  "ex-cet-fai-01": {
    "illa": "Faial",
    "sub": "cetacis",
    "nom": "Avistament de cetacis",
    "zona": "Horta",
    "emoji": "🐋",
    "destacat": false,
    "info": "Zodiac",
    "sortides": "8:30h i 14:30h",
    "durada": "3-4h",
    "preu": 80.0,
    "empresa": "https://www.norbertodiver.pt/activity/whale-and-dolphin-watch/"
  },
  "ex-cet-fai-02": {
    "illa": "Faial",
    "sub": "cetacis",
    "nom": "Avistament de cetacis",
    "zona": "Horta",
    "emoji": "🐋",
    "destacat": false,
    "info": "Zodiac",
    "sortides": "8:30h i 14:30h",
    "durada": "3-4h",
    "preu": 84.62,
    "empresa": "https://azoresexperiences.com/en/whale-and-dolphin-watching/"
  },
  "ex-cet-fai-03": {
    "illa": "Faial",
    "sub": "cetacis",
    "nom": "Avistament de cetacis",
    "zona": "Horta",
    "emoji": "🐋",
    "destacat": false,
    "info": "Zodiac",
    "sortides": "8:30h i 14:30h",
    "durada": "3,5h",
    "preu": 84.14,
    "empresa": "https://www.diveazores.net/service-whale-watching/"
  },
  "ex-cet-fai-04": {
    "illa": "Faial",
    "sub": "cetacis",
    "nom": "Avistament de cetacis",
    "zona": "Horta",
    "emoji": "🐋",
    "destacat": false,
    "info": "Zodiac",
    "sortides": "9h i 14h",
    "durada": "3h",
    "preu": 80.0,
    "empresa": "https://www.naturalist.pt/uk-tour-azores-whale-watching"
  },
  "ex-cet-fai-05": {
    "illa": "Faial",
    "sub": "cetacis",
    "nom": "Avistament de cetacis",
    "zona": "Horta",
    "emoji": "🐋",
    "destacat": false,
    "info": "Catamarà",
    "sortides": "Matí i Tarda",
    "durada": "3-4h",
    "preu": 80.0,
    "empresa": "https://www.petercafesport.com/whale-watching/?lang=en"
  },
  "ex-est-fai-01": {
    "illa": "Faial",
    "sub": "estrelles",
    "nom": "Estrelles - Caldeira do Faial",
    "zona": "Caldeira do Faial",
    "emoji": "✨",
    "destacat": false,
    "info": "A uns 900m, molt fosc",
    "sortides": null,
    "durada": null,
    "preu": null,
    "empresa": null
  },
  "ex-est-fai-02": {
    "illa": "Faial",
    "sub": "estrelles",
    "nom": "Estrelles - Capelinhos",
    "zona": "Capelinhos",
    "emoji": "✨",
    "destacat": false,
    "info": "Paisatge lunar i cel estrellat",
    "sortides": null,
    "durada": null,
    "preu": null,
    "empresa": null
  }
};
