/* ============================================================
   IMPRESCINDIBLES-DATA.JS  ·  Açores 2026
   25 llocs imprescindibles de les 4 illes
   Fotos: img/imprescindibles/PREFIX_01.jpg ... PREFIX_NN.jpg
   ============================================================ */

const IMPRESCINDIBLES = [

  /* ══════════════════════════════════════════════════════
     SÃO MIGUEL
  ══════════════════════════════════════════════════════ */
  {
    illa: 'São Miguel',
    id: 'sete-cidades',
    nom: 'Lagoa das Sete Cidades',
    emoji: '🌊',
    desc: 'El símbol de São Miguel: dos llacs volcànics units per un pont, un de verd i un de blau. El mirador Vista do Rei ofereix la postal més icònica dels Açores. La llegenda diu que els llacs van néixer de les llàgrimes d\'un pastor i una princesa.',
    coords: [37.8567, -25.7833],
    maps: 'https://maps.google.com/?q=37.8567,-25.7833',
    fotos: 0,
    prefix: 'SeteCidades',
  },
  {
    illa: 'São Miguel',
    id: 'furnas',
    nom: 'Caldeira das Furnas',
    emoji: '♨️',
    desc: 'La vall geotèrmica més espectacular dels Açores. Fumaroles, llot bullent i la famosa cozido das Furnas: un guisat cuit durant hores enterrat al terra volcànic. Un paisatge que sembla d\'un altre planeta, envoltat de jardins exuberants.',
    coords: [37.7726, -25.3192],
    maps: 'https://maps.google.com/?q=37.7726,-25.3192',
    fotos: 0,
    prefix: 'Furnas',
  },
  {
    illa: 'São Miguel',
    id: 'lagoa-fogo',
    nom: 'Lagoa do Fogo',
    emoji: '🔥',
    desc: 'El llac més salvatge i pur de São Miguel, encaixat al cràter del volcà Água de Pau. Sense infraestructura turística, amb platges de sorra volcànica i aigües cristal·lines. Quan no hi ha boira, la vista des del mirador és absolutament esplèndida.',
    coords: [37.7706, -25.4694],
    maps: 'https://maps.google.com/?q=37.7706,-25.4694',
    fotos: 0,
    prefix: 'LagoaFogo',
  },
  {
    illa: 'São Miguel',
    id: 'madrugada',
    nom: 'Ponta da Madrugada',
    emoji: '🌅',
    desc: 'L\'extrem est de São Miguel, famós per ser un dels primers llocs d\'Europa on surt el sol. Penya-segats imponents sobre l\'oceà, vegetació exuberant i una solitud absoluta. Ideal per veure l\'alba amb vistes a l\'Atlàntic obert.',
    coords: [37.7411, -25.0978],
    maps: 'https://maps.google.com/?q=37.7411,-25.0978',
    fotos: 0,
    prefix: 'Madrugada',
  },
  {
    illa: 'São Miguel',
    id: 'terra-nostra',
    nom: 'Terra Nostra Garden',
    emoji: '🌿',
    desc: 'Un dels jardins botànics més antics i bonics de l\'hemisferi nord, fundat al segle XVIII a Furnas. La seva atracció principal és la piscina termal natural de color ferruginós daurat, envoltada de sequoies centenàries, helechos tropicals i camèlies.',
    coords: [37.7728, -25.3214],
    maps: 'https://maps.google.com/?q=37.7728,-25.3214',
    fotos: 0,
    prefix: 'TerraNostra',
  },
  {
    illa: 'São Miguel',
    id: 'caldeira-velha',
    nom: 'Caldeira Velha',
    emoji: '💧',
    desc: 'Un racó màgic al cor del bosc laurisilva: cascades que cauen sobre piscines naturals termals d\'aigües verdoses. La temperatura de l\'aigua ronda els 38°C tot l\'any. Un bany aquí, envoltat de falgueres gegants i llum filtrada pels arbres, és una experiència inoblidable.',
    coords: [37.8156, -25.4811],
    maps: 'https://maps.google.com/?q=37.8156,-25.4811',
    fotos: 0,
    prefix: 'CaldeiraVelha',
  },
  {
    illa: 'São Miguel',
    id: 'ponta-delgada',
    nom: 'Ponta Delgada',
    emoji: '🏛️',
    desc: 'La capital dels Açores és una ciutat barroca encantadora. Les Portes da Cidade, símbol de l\'arxipèlag, la imponent església de Sant Sebastià, el mercat de la Graça ple de productes locals i el port on arriben transatlàntics. Una tarda passejar-hi és imprescindible.',
    coords: [37.7412, -25.6756],
    maps: 'https://maps.google.com/?q=37.7412,-25.6756',
    fotos: 0,
    prefix: 'PontaDelgada',
  },
  {
    illa: 'São Miguel',
    id: 'ribeira-caldeiroes',
    nom: 'Parque Natural da Ribeira dos Caldeirões',
    emoji: '🌳',
    desc: 'Un dels parcs naturals més espectaculars de São Miguel, al nord de l\'illa. Una sèrie de cascades successives cau enmig d\'una vegetació subtropical exuberant. Molins d\'aigua restaurats, ponts de pedra i una ruta senzilla que segueix el curs del riu entre helechos gegants.',
    coords: [37.8614, -25.3353],
    maps: 'https://maps.google.com/?q=37.8614,-25.3353',
    fotos: 0,
    prefix: 'RibeiraCaldeiroes',
  },
  {
    illa: 'São Miguel',
    id: 'vila-franca',
    nom: 'Ilhéu de Vila Franca do Campo',
    emoji: '🏝️',
    desc: 'Un illot volcànic a 1 km de la costa, format per un cràter submergit que crea una laguna natural circular d\'aigües turqueses protegides. L\'accés és per barca des de Vila Franca do Campo. L\'entrada és limitada i cal reservar; és un dels banys de mar més singulars dels Açores.',
    coords: [37.7139, -25.4369],
    maps: 'https://maps.google.com/?q=37.7139,-25.4369',
    fotos: 0,
    prefix: 'IlheuVilaFranca',
  },
  {
    illa: 'São Miguel',
    id: 'gruta-carvao',
    nom: 'Gruta do Carvão',
    emoji: '🕳️',
    desc: 'El túnel de lava més llarg accessible dels Açores, al cor de Ponta Delgada. Formada fa uns 1.000 anys per colades de lava, té més de 2 km de llargada total. Les visites guiades mostren formacions geològiques úniques: estalagmites de lava, parets vidrioses i galeries de diferents alçades.',
    coords: [37.7478, -25.6517],
    maps: 'https://maps.google.com/?q=37.7478,-25.6517',
    fotos: 0,
    prefix: 'GrutaCarvao',
  },
  {
    illa: 'São Miguel',
    id: 'poco-azul',
    nom: 'Poço Azul',
    emoji: '💙',
    desc: 'Una piscina natural d\'aigües d\'un blau intens, formada a l\'interior d\'un bosc exuberant al nord de São Miguel. L\'accés requereix una caminada breu per un sender forestal. Quan el sol entra a plom, l\'aigua brilla d\'un color turquesa irreal que justifica plenament el nom.',
    coords: [37.8578, -25.3981],
    maps: 'https://maps.google.com/?q=37.8578,-25.3981',
    fotos: 0,
    prefix: 'PocoAzul',
  },
  {
    illa: 'São Miguel',
    id: 'ferraria',
    nom: 'Ponta da Ferraria',
    emoji: '🌋',
    desc: 'A l\'extrem oest de São Miguel, on l\'oceà es barreja amb aigües termals volcàniques. Unes piscines naturals formades per lava es mantenen calentes gràcies a les emanacions del subsòl. La temperatura de l\'aigua canvia amb la marea: quan la mar puja, l\'aigua es refresca.',
    coords: [37.8628, -25.8522],
    maps: 'https://maps.google.com/?q=37.8628,-25.8522',
    fotos: 0,
    prefix: 'Ferraria',
  },

  /* ══════════════════════════════════════════════════════
     SÃO JORGE
  ══════════════════════════════════════════════════════ */
  {
    illa: 'São Jorge',
    id: 'faja-cubres',
    nom: 'Fajã dos Cubres',
    emoji: '🦅',
    desc: 'Una de les fajãs més accessibles i boniques de São Jorge. Una llacuna d\'aigües tranquil·les envoltada de vegetació densa, ideal per observar aus. La fajã és una plataforma plana formada per despreniments de penya-segat al llarg de milions d\'anys, un fenomen únic als Açores.',
    coords: [38.6578, -27.9458],
    maps: 'https://maps.google.com/?q=38.6578,-27.9458',
    fotos: 0,
    prefix: 'FajaCubres',
  },
  {
    illa: 'São Jorge',
    id: 'faja-santo-cristo',
    nom: 'Fajã da Caldeira de Santo Cristo',
    emoji: '🦪',
    desc: 'La fajã més famosa dels Açores, accessible a peu per un sender de muntanya espectacular des de Fajã dos Cubres. Únic lloc del món on creixen les cloïsses dos Açores, un mol·lusc exclusiu. Un petit paradís aïllat amb cases de pescadors, platges de còdols i una llacuna singular.',
    coords: [38.6611, -27.9669],
    maps: 'https://maps.google.com/?q=38.6611,-27.9669',
    fotos: 0,
    prefix: 'FajaSantoCristo',
  },
  {
    illa: 'São Jorge',
    id: 'faja-ouvidor',
    nom: 'Fajã do Ouvidor i Piscines Naturals de Simão Dias',
    emoji: '🏊',
    desc: 'Una fajã de gran bellesa a la costa nord de São Jorge, accessible per un sender que baixa pels penya-segats. Al seu peu hi ha les piscines naturals de Simão Dias, excavades a la roca volcànica i banyades per l\'Atlàntic. Les vistes des de dalt, amb els penya-segats i l\'oceà, són impressionants.',
    coords: [38.6706, -28.0289],
    maps: 'https://maps.google.com/?q=38.6706,-28.0289',
    fotos: 0,
    prefix: 'FajaOuvidor',
  },
  {
    illa: 'São Jorge',
    id: 'sete-fontes',
    nom: 'Parque Florestal Sete Fontes',
    emoji: '🌲',
    desc: 'Un bosc frondós a les altituds de São Jorge, creuat per set fonts d\'aigüa natural. Rutes de senderisme tranquil·les entre criptomèries japoneses, helechos gegants i hortènsies blaves. Un espai de pau i frescor que contrasta amb la rudesa dels penya-segats de la costa.',
    coords: [38.6578, -28.1211],
    maps: 'https://maps.google.com/?q=38.6578,-28.1211',
    fotos: 0,
    prefix: 'SeteFontes',
  },

  /* ══════════════════════════════════════════════════════
     PICO
  ══════════════════════════════════════════════════════ */
  {
    illa: 'Pico',
    id: 'montanha-pico',
    nom: 'Montanha do Pico',
    emoji: '⛰️',
    desc: 'El cim més alt de Portugal i de tot l\'Atlàntic nord: 2.351 metres sobre el mar. L\'ascensió dura entre 3 i 5 hores anada, requereix guia obligatori i reserva prèvia. Des del cràter, en dies clars, es veuen totes les illes del grup Central. Una experiència física i visual única.',
    coords: [38.4694, -28.4017],
    maps: 'https://maps.google.com/?q=38.4694,-28.4017',
    fotos: 0,
    prefix: 'MontanhaPico',
  },
  {
    illa: 'Pico',
    id: 'cultura-vinha',
    nom: 'Paisagem da Cultura da Vinha',
    emoji: '🍇',
    desc: 'Patrimoni de la Humanitat per la UNESCO. Un paisatge únic format per milers de murs de pedra volcànica negra (currais) que protegeixen les vinyes del vent atlàntic. El vi de Pico, el Verdelho, és un dels vins d\'illa més antics i apreciats del món. La millor hora per fotografiar-lo: la posta de sol.',
    coords: [38.5578, -28.2261],
    maps: 'https://maps.google.com/?q=38.5578,-28.2261',
    fotos: 0,
    prefix: 'CulturaVinha',
  },
  {
    illa: 'Pico',
    id: 'lagoa-caiado',
    nom: 'Lagoa do Caiado',
    emoji: '🏞️',
    desc: 'Un llac de muntanya tranquil i poc visitat, envoltat de bosc i amb vistes al volcà. Ideal per fer una caminada tranquil·la allunyada del turisme. La seva situació en altitud garanteix temperatures fresques fins i tot a l\'estiu i unes vistes privilegiades sobre el paisatge de Pico.',
    coords: [38.4839, -28.3544],
    maps: 'https://maps.google.com/?q=38.4839,-28.3544',
    fotos: 0,
    prefix: 'LagoaCaiado',
  },
  {
    illa: 'Pico',
    id: 'piscines-arcos',
    nom: 'Piscines Naturals de Arcos',
    emoji: '🌊',
    desc: 'Les piscines naturals més ben condicionades de Pico, formades per la lava que s\'ha endinsat al mar creant badies naturals protegides. Aigües netes i transparents amb fons de roca volcànica. Un entorn pur, sense artificialitat, on nedar amb vistes directes a l\'oceà obert.',
    coords: [38.5411, -28.4197],
    maps: 'https://maps.google.com/?q=38.5411,-28.4197',
    fotos: 0,
    prefix: 'PiscinesArcos',
  },
  {
    illa: 'Pico',
    id: 'cetacis',
    nom: 'Avistament de cetacis',
    emoji: '🐋',
    desc: 'Els Açores són un dels millors llocs del món per veure balenes i dofins en llibertat. Des de Pico, antics vigies de baleines localitzen els animals i guien les embarcacions. És possible veure cap a 20 espècies, incloent el catxalot, el rorqual comú i diverses espècies de dofins. Cal reservar amb antelació.',
    coords: [38.5167, -28.3167],
    maps: 'https://maps.google.com/?q=38.5167,-28.3167',
    fotos: 0,
    prefix: 'Cetacis',
  },

  /* ══════════════════════════════════════════════════════
     FAIAL
  ══════════════════════════════════════════════════════ */
  {
    illa: 'Faial',
    id: 'caldeira-faial',
    nom: 'Caldeira do Faial',
    emoji: '🌋',
    desc: 'Un cràter volcànic gegant de 2 km de diàmetre i 400 metres de profunditat, cobert de bosc de criptomèries. La ruta circular pel vora del cràter (5 km) és una de les millors caminades dels Açores, amb vistes sobre tota l\'illa i, en dies clars, sobre el Pico al fons.',
    coords: [38.5906, -28.7008],
    maps: 'https://maps.google.com/?q=38.5906,-28.7008',
    fotos: 0,
    prefix: 'CaldeiraFaial',
  },
  {
    illa: 'Faial',
    id: 'capelinhos',
    nom: 'Capelinhos',
    emoji: '🌑',
    desc: 'El lloc més singular de Faial: un volcà que va erupcionar entre 1957 i 1958 enmig de l\'oceà, creant nova terra i sepultant el far de Capelinhos fins a la meitat. El paisatge resultant és absolutament lunar: cendres, lava i el far mig enterrat. El museu adjacent, soterrani, és excel·lent.',
    coords: [38.5931, -28.8331],
    maps: 'https://maps.google.com/?q=38.5931,-28.8331',
    fotos: 0,
    prefix: 'Capelinhos',
  },
  {
    illa: 'Faial',
    id: 'horta-marina',
    nom: 'Horta Marina',
    emoji: '⚓',
    desc: 'La marina de Horta és la més famosa de l\'Atlàntic nord, escala obligatòria dels veliers transocèanics. Per tradició, cada tripulació pinta el seu emblema a les parets i el moll: milers de murals colorits cobreixen cada centímetre de les superfícies. El Café Sport, obert des del 1918, és la seva ànima.',
    coords: [38.5328, -28.6236],
    maps: 'https://maps.google.com/?q=38.5328,-28.6236',
    fotos: 0,
    prefix: 'HortaMarina',
  },
  {
    illa: 'Faial',
    id: 'monte-guia',
    nom: 'Monte da Guia',
    emoji: '🔭',
    desc: 'Un con volcànic al sud de Horta que forma una península natural. La pujada a peu dura uns 20 minuts i recompensa amb una vista panoràmica de 360°: Horta als peus, el Pico dominant l\'horitzó al davant, i São Jorge i Graciosa a la llunyania. El millor mirador de Faial, especialment al capvespre.',
    coords: [38.5117, -28.6242],
    maps: 'https://maps.google.com/?q=38.5117,-28.6242',
    fotos: 0,
    prefix: 'MonteGuia',
  },
];

/* Illes en ordre de visita */
const ILLES_ORDRE = ['São Miguel', 'São Jorge', 'Pico', 'Faial'];

const ILLES_CONFIG = {
  'São Miguel': {
    emoji: '🌋',
    color: '#e74c3c',
    colorSuau: 'rgba(231,76,60,0.12)',
    colorBorde: 'rgba(231,76,60,0.3)',
    coords: [37.78, -25.50],
    zoom: 10,
  },
  'São Jorge': {
    emoji: '🏔️',
    color: '#27ae60',
    colorSuau: 'rgba(39,174,96,0.12)',
    colorBorde: 'rgba(39,174,96,0.3)',
    coords: [38.65, -28.05],
    zoom: 11,
  },
  'Pico': {
    emoji: '⛰️',
    color: '#8e44ad',
    colorBorde: 'rgba(142,68,173,0.3)',
    colorSuau: 'rgba(142,68,173,0.12)',
    coords: [38.47, -28.35],
    zoom: 11,
  },
  'Faial': {
    emoji: '⚓',
    color: '#2980b9',
    colorSuau: 'rgba(41,128,185,0.12)',
    colorBorde: 'rgba(41,128,185,0.3)',
    coords: [38.57, -28.72],
    zoom: 11,
  },
};
